#
# Module manifest for module 'PsDBAid'
#
# Generated by: Wayne Teutenberg
#
# Generated on: 12/07/2019
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PsDBAid.psm1'

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = '738f06d4-4d46-45c9-93d1-8143f50be889'

# Author of this module
Author = 'Wayne Teutenberg'

# Copyright statement for this module
Copyright = '(c) 2019 Wayne Teutenberg. All rights reserved.'

# Description of the functionality provided by this module
Description = 'This is a helper PowerShell module for SQL Server administrators.'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(
    @{ ModuleName = 'SqlServer'; ModuleVersion = '21.1.18121'; }
    @{ ModuleName = 'SqlServerDsc'; ModuleVersion = '12.4.0.0'; }
    #@{ ModuleName = 'ReportingServicesTools'; ModuleVersion = '0.0.5.0' }
)

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
#NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = ''

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = ''

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = ''

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
#DefaultCommandPrefix = 'Dbaid'
}

